name: cmake

on: [push, pull_request]

jobs:

  ubuntu-build:
    runs-on: ${{ matrix.ubuntu-distro }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-distro:
          - ubuntu-20.04
          - ubuntu-22.04

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Install apt packages
        run: |
              sudo apt update && sudo apt -y install \
                software-properties-common \
                qtbase5-dev \
                libqt5svg5-dev \
                libqt5websockets5-dev \
                libqt5opengl5-dev \
                libqt5x11extras5-dev \
                libprotoc-dev \
                libzmq3-dev

      - name: Build Plotjuggler
        run: |
            cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler;
            cmake --build build --target install

  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version:
          - 'windows-2019'
          - 'windows-latest'
    env:
      CXXFLAGS: /MP

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt_installation/'

      - name: Build Plotjuggler
        shell: pwsh
        run: >
          cmake -Ax64 -T host=x64 -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler;
          cmake --build build --target install
